app:
  server:
    name: "0.0.0.0"
    port: 7860

file_extensions:
    subtitles: ".srt"
    audio: ".mp3"

openai:
  model: "gpt-4"
  max_tokens: 1250
  temperature: 0.5

interface:
  max_width: 800
  styles:
    phrase_display:
      font_size: 24
      margin: 20
    translation_display:
      margin_top: 20
      padding: 15
      background: "#f5f5f5"
      border_radius: 8
    navigation_buttons:
      gap: 10
      margin: 10

translator:
  source_language: "French"
  target_language: "German"
  prompts:
    system: >
      You are a helpful assistant that translates {source_language} to {target_language} 
      and explains words that might be unfamiliar to a {target_language} learner. 
      You speak only {source_language} and {target_language}.
    user: >
      Translate the following {source_language} phrase into {target_language}, 
      and then list the words that a {target_language} learner might not know, 
      providing short translations for each.

      Phrase: "{text}"
