# config/default.yml
paths:
  data_dir: "data/book"
  chapter: "aliceaupays_03_carroll_64kb"
  book_title: "Alice au pays des merveilles"
  book_cover: "data/book/cover2.png"

server:
  host: "0.0.0.0"
  port: 7860

openai:
  model: "gpt-4"
  max_tokens: 1250
  temperature: 0.5

translation:
  source_language: "French"
  target_language: "German"
  prompts:
    system: >
      You are a helpful assistant that translates {source_language} to {target_language} 
      and explains words that might be unfamiliar to a {target_language} learner. 
      In your response, the only languages you use are {source_language} and {target_language}!
      Even if this prompt is written in English.
    user: >
      Translate the following {source_language} phrase into {target_language}, 
      and then list the words that a {target_language} learner might not know, 
      providing short translations for each, don't translate all words, only difficult ones.

      Phrase: "{text}"

interface:
  styles: |
    .container {
        max-width: 800px !important;
        margin: auto !important;
        padding: 20px !important;
    }
    #phrase_display {
        font-size: 24px;
        margin: 20px 0;
        text-align: center;
    }
    #translation_display {
        margin-top: 20px;
        padding: 15px;
        background: #f5f5f5;
        border-radius: 8px;
    }
    .navigation-buttons {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin: 10px 0;
    }